name: 04_GFWList 域名解析（兼容版）

on:
  schedule:
    - cron: '30 20 * * *'  # UTC 20:30 = 北京时间 04:30
  workflow_dispatch:

jobs:
  resolve-dns:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 下载GFWList原始文件
        run: |
          curl -sSL https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt -o gfwlist_original.txt
          if [ ! -s gfwlist_original.txt ]; then
            echo "错误：GFWList下载失败"
            exit 1
          fi
          echo "GFWList下载完成"
          
      - name: 解码GFWList
        run: |
          if [ ! -f gfwlist_original.txt ]; then
            echo "错误：未找到原始文件"
            exit 1
          fi
          base64 -d gfwlist_original.txt > gfwlist_decoded.txt 2>/dev/null
          if [ ! -s gfwlist_decoded.txt ]; then
            echo "错误：Base64解码失败"
            exit 1
          fi
          echo "解码完成"
          
      - name: 提取域名
        run: |
          if [ ! -f gfwlist_decoded.txt ]; then
            echo "错误：未找到解码文件"
            exit 1
          fi
          
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('gfwlist_decoded.txt', 'utf-8');
            const lines = content.split('\\n');
            const domains = new Set();
            
            for (const line of lines) {
              if (!line.trim() || line.startsWith('!') || line.startsWith('[') || line.startsWith('@@')) continue;
              
              let domain = line.replace('||', '').replace('|', '').split('/')[0].trim();
              domain = domain.replace('*.', '');
              const match = domain.match(/[a-zA-Z0-9][-a-zA-Z0-9._]*\\.[a-zA-Z]{2,}$/);
              
              if (match) {
                domains.add(match[0]);
              }
            }
            
            fs.writeFileSync('gfwlist_domains.txt', [...domains].sort().join('\\n'));
            console.log(\`提取完成，域名数量: \${domains.size}\`);
          "
          
      - name: 解析域名获取IP（兼容所有Node.js版本）
        run: |
          if [ ! -f gfwlist_domains.txt ]; then
            echo "错误：未找到域名文件"
            exit 1
          fi
          
          node -e "
            const fs = require('fs');
            const dns = require('dns');
            const { promisify } = require('util');
            const domains = fs.readFileSync('gfwlist_domains.txt', 'utf-8').split('\\n').filter(d => d.trim());
            const ips = new Set();
            const failedDomains = [];
            const dnsServers = ['8.8.8.8', '1.1.1.1', '9.9.9.9', '84.200.69.80', '8.20.247.20'];
            let successCount = 0;
            let failCount = 0;
            
            console.log(\`开始解析 \${domains.length} 个域名\`);
            
            // 封装带超时的解析函数（兼容所有Node.js版本）
            async function resolveWithTimeout(domain, server, timeout = 5000) {
              return new Promise((resolve, reject) => {
                const resolve4 = promisify(dns.resolve4).bind(dns);
                
                const timeoutId = setTimeout(() => {
                  reject(new Error('解析超时'));
                }, timeout);
                
                resolve4(domain, { server })
                  .then(ips => {
                    clearTimeout(timeoutId);
                    resolve(ips);
                  })
                  .catch(error => {
                    clearTimeout(timeoutId);
                    reject(error);
                  });
              });
            }
            
            // 解析单个域名
            async function resolveDomain(domain) {
              for (const server of dnsServers) {
                try {
                  const addresses = await resolveWithTimeout(domain, server, 8000); // 8秒超时
                  for (const ip of addresses) {
                    ips.add(ip);
                  }
                  
                  console.log(\`✓ 解析成功: \${domain} → \${addresses.join(', ')} (服务器: \${server})\`);
                  successCount++;
                  return;
                } catch (error) {
                  console.log(\`✗ 解析失败 (\${server}): \${domain} → \${error.message}\`);
                  continue;
                }
              }
              
              failedDomains.push(domain);
              failCount++;
            }
            
            // 并行解析（限制并发数避免资源耗尽）
            async function parallelResolve(domains, concurrency = 10) {
              const results = [];
              for (let i = 0; i < domains.length; i += concurrency) {
                const batch = domains.slice(i, i + concurrency);
                const batchResults = await Promise.all(batch.map(resolveDomain));
                results.push(...batchResults);
                console.log(\`完成批次 \${i/concurrency + 1} / \${Math.ceil(domains.length/concurrency)}\`);
              }
              return results;
            }
            
            parallelResolve(domains)
              .then(() => {
                fs.writeFileSync('gfwlist_ips.txt', [...ips].sort().join('\\n'));
                fs.writeFileSync('failed_domains.txt', failedDomains.join('\\n'));
                
                console.log(\`解析完成:\`);
                console.log(\`  成功: \${successCount} 个域名\`);
                console.log(\`  失败: \${failCount} 个域名\`);
                console.log(\`  生成IP: \${ips.size} 个\`);
              })
              .catch(error => {
                console.error(\`解析过程出错: \${error.message}\`);
                process.exit(1);
              });
          "
          
      - name: 验证结果文件
        run: |
          if [ ! -f gfwlist_ips.txt ]; then
            echo "错误：未生成IP文件"
            exit 1
          fi
          
          ip_count=$(wc -l gfwlist_ips.txt | awk '{print $1}')
          echo "IP文件包含 $ip_count 个IP"
          
      - name: 提交结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add gfwlist_ips.txt failed_domains.txt
          if git diff --staged --quiet; then
            echo "没有新内容更新"
          else
            commit_msg="更新GFWList IP列表: $(date +'%Y-%m-%d %H:%M')"
            git commit -m "$commit_msg"
            git push
            echo "已推送更新"
          fi
