name: 04_定时解析 GFWList 域名到 IP（修复版）

on:
  schedule:
    - cron: '30 20 * * *'  # UTC 20:30 = 北京时间 04:30
  workflow_dispatch:

jobs:
  resolve-gfwlist:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 安装 DNS 解析工具
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils
          if [ $? -ne 0 ]; then
            echo "错误：工具安装失败"
            exit 1
          fi
          
      - name: 检查域名文件是否存在
        run: |
          if [ ! -f gfwlist_domains.txt ]; then
            echo "错误：未找到 gfwlist_domains.txt，请先提取域名和IP"
            exit 1
          fi
          domain_count=$(wc -l gfwlist_domains.txt | awk '{print $1}')
          echo "找到 $domain_count 个待解析条目"
          
      - name: 解析域名获取 IP 地址
        run: |
          > gfwlist_ips.txt  # 清空并初始化IP文件
          dns_servers=("8.8.8.8" "1.1.1.1")
          success_count=0
          fail_count=0
          
          echo "开始解析，使用 DNS 服务器: ${dns_servers[*]}"
          
          while IFS= read -r entry; do
            if [ -z "$entry" ]; then continue; fi
            
            # 检查是否为IP地址，若是则直接添加
            if [[ $entry =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              echo "$entry" >> gfwlist_ips.txt
              echo "✓ 直接添加 IP: $entry"
              ((success_count++))
              continue
            fi
            
            # 域名解析逻辑
            echo -n "解析域名 $entry..."
            ip=""
            
            # 尝试多个DNS服务器
            for dns in "${dns_servers[@]}"; do
              ip=$(dig +short +time=3 +tries=2 @$dns "$entry" A 2>/dev/null)  # 隐藏dig错误输出
              if [ -n "$ip" ]; then
                break
              fi
            done
            
            if [ -n "$ip" ]; then
              echo "$ip" >> gfwlist_ips.txt
              echo " 成功 ($ip)"
              ((success_count++))
            else
              echo " 失败"
              ((fail_count++))
            fi
            
            # 控制解析频率
            sleep 0.5
          done < gfwlist_domains.txt
          
          # 去重并排序IP列表（添加错误处理）
          echo "正在对IP去重排序..."
          if [ -f gfwlist_ips.txt ] && [ $(wc -l gfwlist_ips.txt) -gt 0 ]; then
            sort -u gfwlist_ips.txt -o gfwlist_ips.txt
            if [ $? -ne 0 ]; then
              echo "错误：IP去重排序失败"
              exit 1
            fi
          else
            echo "警告：IP文件为空，跳过去重"
          fi
          
          # 统计结果（添加错误处理）
          echo "正在统计解析结果..."
          final_ip_count=0
          if [ -f gfwlist_ips.txt ]; then
            final_ip_count=$(wc -l gfwlist_ips.txt | awk '{print $1}')
            if [ $? -ne 0 ]; then
              echo "错误：IP数量统计失败"
              exit 1
            fi
          fi
          
          echo "解析完成："
          echo "  成功解析: $success_count 个"
          echo "  解析失败: $fail_count 个"
          echo "  最终IP数量: $final_ip_count 个"
          
      - name: 验证结果文件
        run: |
          if [ ! -f gfwlist_ips.txt ]; then
            echo "错误：未生成IP文件"
            exit 1
          fi
          
          ip_count=$(wc -l gfwlist_ips.txt | awk '{print $1}')
          echo "IP文件包含 $ip_count 个条目"
          
          # 显示前10个IP（调试用）
          echo "前10个IP："
          head -n 10 gfwlist_ips.txt
          
      - name: 提交结果文件
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add gfwlist_ips.txt
          if git diff --staged --quiet; then
            echo "没有新内容更新"
          else
            commit_msg="更新 GFWList IP 列表: $(date +'%Y-%m-%d %H:%M')"
            git commit -m "$commit_msg"
            git push
            echo "已推送更新"
          fi
