name: 04_定时解析 GFWList 域名到 IP（最终稳定版）

on:
  schedule:
    - cron: '30 20 * * *'  # UTC 20:30 = 北京时间 04:30
  workflow_dispatch:

jobs:
  resolve-gfwlist:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 安装 DNS 解析工具
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils
          if [ $? -ne 0 ]; then
            echo "错误：工具安装失败"
            exit 1
          fi
          
      - name: 检查域名文件是否存在
        run: |
          if [ ! -f gfwlist_domains.txt ]; then
            echo "错误：未找到 gfwlist_domains.txt，请先提取域名和IP"
            exit 1
          fi
          domain_count=$(wc -l gfwlist_domains.txt | awk '{print $1}')
          echo "找到 $domain_count 个待解析条目"
          
      - name: 解析域名获取 IP 地址
        run: |
          > gfwlist_ips.txt
          dns_servers=("8.8.8.8" "8.8.4.4" "1.1.1.1" "1.0.0.1" "9.9.9.9" "149.112.112.112" "84.200.69.80" "8.20.247.20")
          success_count=0
          fail_count=0
          
          echo "开始解析，使用 DNS 服务器: ${dns_servers[*]}"
          
          line_num=0
          while IFS= read -r entry; do
            line_num=$((line_num+1))
            if [ -z "$entry" ]; then 
              echo "行 $line_num: 空行，跳过"
              continue 
            fi
            
            # 处理IP地址
            if [[ $entry =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              echo "$entry" >> gfwlist_ips.txt
              echo "行 $line_num: ✓ 直接添加 IP: $entry"
              ((success_count++))
              continue
            fi
            
            # 域名解析
            echo -n "行 $line_num: 解析域名 $entry..."
            ips=""
            resolved=false
            
            # 尝试所有DNS服务器
            for dns in "${dns_servers[@]}"; do
              ips=$(dig +short +time=5 +tries=3 @$dns "$entry" A 2>/dev/null)
              if [ -n "$ips" ]; then
                resolved=true
                break
              fi
            done
            
            if [ "$resolved" = true ]; then
              # 清理并分割IP
              ip_list=$(echo "$ips" | tr -d '\r\n\t' | sed 's/  */ /g' | sed 's/^ //; s/ $//')
              valid_ips=$(echo "$ip_list" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
              
              if [ -n "$valid_ips" ]; then
                echo "$valid_ips" >> gfwlist_ips.txt
                echo " 成功 ($valid_ips)"
                ((success_count++))
              else
                echo " 失败（解析出无效IP）"
                ((fail_count++))
              fi
            else
              echo " 失败（所有DNS均无法解析）"
              ((fail_count++))
            fi
            
            sleep 1
          done < gfwlist_domains.txt
          
          # 去重排序（带详细错误处理）
          echo "==== 去重排序 IP ===="
          if [ -f gfwlist_ips.txt ]; then
            # 检查文件是否为空
            if [ -s gfwlist_ips.txt ]; then
              sort -u gfwlist_ips.txt > temp.txt
              if [ $? -ne 0 ]; then
                echo "错误：sort 去重失败，文件内容："
                cat gfwlist_ips.txt
                exit 1
              fi
              mv temp.txt gfwlist_ips.txt
            else
              echo "警告：IP文件为空，跳过去重"
            fi
          else
            echo "错误：IP文件不存在"
            exit 1
          fi
          
          # 统计结果（分步处理）
          echo "==== 统计解析结果 ===="
          final_ip_count=0
          if [ -f gfwlist_ips.txt ]; then
            final_ip_count=$(wc -l gfwlist_ips.txt)
            if [ $? -ne 0 ]; then
              echo "错误：wc 统计失败"
              exit 1
            fi
          else
            echo "错误：IP文件丢失"
            exit 1
          fi
          
          echo "解析完成："
          echo "  成功解析: $success_count 个域名"
          echo "  解析失败: $fail_count 个域名"
          echo "  最终IP数量: $final_ip_count 个"
          
      - name: 验证结果文件
        run: |
          if [ ! -f gfwlist_ips.txt ]; then
            echo "错误：未生成IP文件"
            exit 1
          fi
          
          ip_count=$(wc -l gfwlist_ips.txt)
          echo "IP文件包含 $ip_count 个有效IP，每行一个"
          
          # 显示前10个IP
          if [ $ip_count -gt 0 ]; then
            echo "==== 前10个IP ===="
            head -n 10 gfwlist_ips.txt
          else
            echo "警告：IP文件为空"
          fi
          
      - name: 提交结果文件（优化版）
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 确保文件可读写
          chmod 777 gfwlist_ips.txt
          
          git add gfwlist_ips.txt
          if git diff --staged --quiet; then
            echo "没有新内容更新"
          else
            commit_msg="更新 GFWList IP 列表: $(date +'%Y-%m-%d %H:%M')"
            git commit -m "$commit_msg" || { echo "提交失败，继续执行" && true; }
            git push || { echo "推送失败，解析已完成" && exit 0; }
          fi
          
      - name: 流程完成确认
        run: |
          echo "==== 解析流程正常完成 ===="
          date
