name: GFWlist 定时转换

on:
  schedule:
    - cron: '0 12 * * *'  # UTC 12:00 = 北京时间 20:00
  workflow_dispatch:

jobs:
  extract-domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 下载 GFWList
        run: |
          wget -q https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt -O gfwlist.txt
          if [ $? -ne 0 ]; then
            echo "错误：GFWList 下载失败"
            exit 1
          fi
          echo "GFWList 下载完成"
          
      - name: 安装依赖工具
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          if [ $? -ne 0 ]; then
            echo "错误：依赖工具安装失败"
            exit 1
          fi
          
      - name: Base64 解码并提取域名
        run: |
          if [ ! -f gfwlist.txt ]; then
            echo "错误：未找到 gfwlist.txt"
            exit 1
          fi
          
          # 解码 Base64 内容
          decoded_content=$(base64 -d gfwlist.txt 2>/dev/null)
          if [ $? -ne 0 ]; then
            echo "错误：Base64 解码失败"
            exit 1
          fi
          
          # 提取域名（处理不同格式的规则）
          echo "正在提取域名..."
          domains=$(echo "$decoded_content" | grep -v '^\[.*\]$' | grep -v '^!.*$' | grep -v '^@@.*$' | \
                   sed 's/^||//' | sed 's/|$//' | sed 's/\/.*//' | \
                   grep -E -o '[a-zA-Z0-9][-a-zA-Z0-9._]*\.[a-zA-Z]{2,}' | \
                   sort -u)
          
          # 保存到文件
          echo "$domains" > gfwlist2dns.txt
          
          # 统计域名数量
          domain_count=$(wc -l gfwlist2dns.txt | awk '{print $1}')
          echo "成功提取 $domain_count 个唯一域名，保存至 gfwlist2dns.txt"
          
      - name: 验证提取结果
        run: |
          if [ ! -f gfwlist2dns.txt ]; then
            echo "错误：未生成域名列表文件"
            exit 1
          fi
          
          # 显示前 10 个域名（调试用）
          echo "前 10 个提取的域名："
          head -n 10 gfwlist2dns.txt
          
      - name: 提交结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add gfwlist2dns.txt
          if git diff --staged --quiet; then
            echo "没有新域名更新"
          else
            commit_msg="更新 GFWList 域名列表: $(date +'%Y-%m-%d')"
            git commit -m "$commit_msg"
            git push
            echo "已推送更新"
          fi
